scg_transport_server:
  container_name: backend
  build: .
  volumes:
    - .:/usr/src/app/
  expose:
    - "9000"
  ports:
    - "9000:9000"
  environment:
    - MONGO_URI=mongodb+srv://dev:Cmcl1ccicqI8XraI@cluster0.zy4m3.mongodb.net/myFirstDatabase?retryWrites=true&w=majority