scg_transport_server:
  container_name: backend
  build: .
  volumes:
    - .:/usr/src/app/
  expose:
    - "9000"
  ports:
    - "9000:9000"
  environment:
    - DEBUG=1
    - DEBUG_MONGO_URI=mongodb+srv://dev:Cmcl1ccicqI8XraI@cluster0.zy4m3.mongodb.net/debugDatabase?retryWrites=true&w=majority
    - MONGO_URI=mongodb+srv://dev:Cmcl1ccicqI8XraI@cluster0.zy4m3.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    - B2_KEY_ID=000c0781e5ac2210000000001
    - B2_APPLICATION_KEY=K000drXGv+azfUeH8qGRiViwnFyij8A